# Generated by Django 6.0.5 on 2026-05-23 12:55

import ats.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', ats.models.EncryptedCharField(max_length=100)),
                ('lastName', ats.models.EncryptedCharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', ats.models.EncryptedCharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppWorkflowDef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('locationIdsJson', models.TextField(default='[]')),
                ('categoryIdsJson', models.TextField(default='[]')),
                ('jobIdsJson', models.TextField(default='[]')),
                ('stepsJson', models.TextField(default='[]')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('userId', models.CharField(blank=True, max_length=255, null=True)),
                ('applicationId', models.CharField(blank=True, max_length=255, null=True)),
                ('metadataJson', models.TextField(default='{}')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('photoUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('globalJobTitle', models.CharField(blank=True, max_length=150, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('htmlContent', models.TextField()),
                ('textContent', models.TextField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='JobAlertSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('globalAlert', models.BooleanField(default=False)),
                ('categories', models.TextField(default='[]')),
                ('locations', models.TextField(default='[]')),
                ('radiusKm', models.IntegerField(blank=True, null=True)),
                ('confirmationToken', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('managementToken', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('lastConfirmedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastAlertSentAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Job Families',
            },
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(default='')),
                ('status', models.CharField(default='published', max_length=50)),
                ('navEnabled', models.BooleanField(default=True)),
                ('navLabel', models.CharField(blank=True, max_length=150, null=True)),
                ('navParent', models.CharField(blank=True, max_length=255, null=True)),
                ('navOrder', models.IntegerField(default=0)),
                ('metaDesc', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyNoticeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('archived', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalentPoolSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('criteria', models.TextField(default='{}')),
                ('consentId', models.CharField(max_length=255)),
                ('expiresAt', models.DateTimeField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiresAt', models.DateTimeField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='ats.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cvStorageId', models.CharField(blank=True, max_length=255, null=True)),
                ('coverLetterTxt', ats.models.EncryptedTextField(blank=True, null=True)),
                ('screeningAnswersJson', models.TextField(default='{}')),
                ('aiScore', models.CharField(blank=True, max_length=10, null=True)),
                ('aiRationale', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='NEW', max_length=50)),
                ('withdrawReason', models.TextField(blank=True, null=True)),
                ('consentTalentPool', models.BooleanField(default=False)),
                ('internalNotes', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ats.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='AILearningSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoryId', models.CharField(blank=True, max_length=255, null=True)),
                ('facilityId', models.CharField(blank=True, max_length=255, null=True)),
                ('feedbackType', models.CharField(max_length=50)),
                ('anonymizedProfileJson', models.TextField(default='{}')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aiLearningSample', to='ats.application')),
            ],
        ),
        migrations.CreateModel(
            name='AppTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='IN_PROGRESS', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appTicket', to='ats.application')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appTickets', to='ats.appworkflowdef')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='ats.facility')),
            ],
        ),
        migrations.AddField(
            model_name='appworkflowdef',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appWorkflows', to='ats.facility'),
        ),
        migrations.CreateModel(
            name='FacilityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.TextField(default='[]')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ats.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduledAt', models.DateTimeField()),
                ('locationType', models.CharField(max_length=50)),
                ('meetingLink', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='ats.application')),
            ],
        ),
        migrations.CreateModel(
            name='JobAlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('metadata', models.TextField(default='{}')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ats.jobalertsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tasksJson', models.TextField(default='[]')),
                ('requirementsJson', models.TextField(default='[]')),
                ('screeningQuestionsJson', models.TextField(default='[]')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('benefits', models.ManyToManyField(blank=True, related_name='jobPostings', to='ats.benefit')),
                ('contactPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobPostings', to='ats.contactperson')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobPostings', to='ats.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobPostings', to='ats.facility')),
                ('jobFamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobPostings', to='ats.jobfamily')),
                ('jobTemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobPostings', to='ats.jobtemplate')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobPostings', to='ats.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobPostings', to='ats.organization')),
                ('workflowState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobPostings', to='ats.workflowstate')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('isBooked', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewSlot', to='ats.application')),
                ('jobPosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewSlots', to='ats.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('jobPosting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approvalTicket', to='ats.jobposting')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='jobPosting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ats.jobposting'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('readStatus', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ats.application')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ats.organization'),
        ),
        migrations.AddField(
            model_name='application',
            name='privacyNoticeVersion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='ats.privacynoticeversion'),
        ),
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobFamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textSnippets', to='ats.jobfamily')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwordHash', models.CharField(default='', max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ats.role')),
            ],
        ),
        migrations.CreateModel(
            name='AppStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stepOrder', models.IntegerField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('actionTakenAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('appTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ats.appticket')),
                ('assignedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appSteps', to='ats.user')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stepOrder', models.IntegerField()),
                ('assignedRoleId', models.CharField(blank=True, max_length=255, null=True)),
                ('assignedUserId', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('actionTakenAt', models.DateTimeField(blank=True, null=True)),
                ('approvalTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ats.approvalticket')),
                ('actionTakenBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvalSteps', to='ats.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stepsJson', models.TextField(default='[]')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='ats.facility')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentContactPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roleTitle', models.CharField(blank=True, max_length=150, null=True)),
                ('contactPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='ats.contactperson')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ats.department')),
            ],
            options={
                'unique_together': {('department', 'contactPerson')},
            },
        ),
        migrations.CreateModel(
            name='FacilityContactPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roleTitle', models.CharField(blank=True, max_length=150, null=True)),
                ('contactPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_links', to='ats.contactperson')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ats.facility')),
            ],
            options={
                'unique_together': {('facility', 'contactPerson')},
            },
        ),
        migrations.CreateModel(
            name='RoleDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scopeType', models.CharField(max_length=50)),
                ('scopeId', models.CharField(blank=True, max_length=255, null=True)),
                ('validFrom', models.DateTimeField()),
                ('validUntil', models.DateTimeField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('delegatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegationsReceived', to='ats.user')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegationsGiven', to='ats.user')),
            ],
            options={
                'unique_together': {('delegator', 'delegatee', 'scopeType', 'scopeId')},
            },
        ),
        migrations.CreateModel(
            name='UserFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_facilities', to='ats.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_facilities', to='ats.user')),
            ],
            options={
                'unique_together': {('user', 'facility')},
            },
        ),
    ]
