# Generated by Django 6.0.7 on 2026-07-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AILearningSample',
        ),
    ]
