# Generated by Django 6.0.7 on 2026-08-02 20:14

import ats.models.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_delete_ailearningsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='severeDisability',
            field=ats.models.base.EncryptedCharField(blank=True, default='', max_length=10),
        ),
    ]
