# Generated by Django 6.0.6 on 2026-07-01 21:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_access', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('facilities', models.ManyToManyField(blank=True, related_name='scopedUsers', to='ats.facility')),
                ('locations', models.ManyToManyField(blank=True, related_name='scopedUsers', to='ats.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
