# Generated by Django 6.0.7 on 2026-08-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_application_severedisability'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='guideCoverageJson',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interviewGuideJson',
            field=models.JSONField(default=list),
        ),
    ]
