# Generated by Django 6.0.6 on 2026-07-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_userscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(default='DIRECT', max_length=50),
        ),
    ]
