# Generated by Django 6.0.7 on 2026-08-04 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0004_interviewfeedback_guidecoveragejson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='actionTakenBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvalSteps', to=settings.AUTH_USER_MODEL),
        ),
    ]
