# Generated by Django 6.0.6 on 2026-07-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0006_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='descriptionEasy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
