# Generated by Django 6.0.6 on 2026-07-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0007_jobposting_descriptioneasy'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entryHash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='prevHash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
