# Generated by Django 6.0.7 on 2026-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0007_emailtemplate_purpose'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['userId'], name='ats_auditlo_userId_275827_idx'),
        ),
    ]
