# Generated by Django 6.0.6 on 2026-07-02 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0008_auditlog_entryhash_auditlog_prevhash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roledelegation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='roledelegation',
            name='delegatee',
        ),
        migrations.RemoveField(
            model_name='roledelegation',
            name='delegator',
        ),
        migrations.AddField(
            model_name='roledelegation',
            name='delegatee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegationsReceived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roledelegation',
            name='delegator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegationsGiven', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='roledelegation',
            unique_together={('delegator', 'delegatee', 'scopeType', 'scopeId')},
        ),
    ]
