# Generated by Django 6.0.6 on 2026-07-02 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0009_alter_roledelegation_delegatee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='ats.jobtemplate'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
