# Generated by Django 6.0.7 on 2026-08-07 13:12

from django.db import migrations

import ats.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0010_dokumentname_verschluesselt'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cvFileName',
            field=ats.models.base.EncryptedCharField(blank=True, default='', max_length=255),
        ),
    ]
