# Generated by Django 6.0.6 on 2026-07-02 07:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0010_jobtemplate_parent_jobtemplate_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taskType', models.CharField(max_length=50)),
                ('payloadJson', models.TextField(default='{}')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('resultJson', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('maxAttempts', models.IntegerField(default=3)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('finishedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
