# Generated by Django 6.0.6 on 2026-07-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0011_aitask'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='altText',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
