# Generated by Django 6.0.6 on 2026-07-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0012_mediaasset_alttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalertsubscription',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobAlerts', to='ats.facility'),
        ),
        migrations.AddField(
            model_name='jobalertsubscription',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
