# Generated by Django 6.0.6 on 2026-07-02 07:54

import ats.models
from django.db import migrations, models




def backfill_email_hash_and_encrypt(apps, schema_editor):
    """Bestandsdaten: Blind-Index berechnen und Alt-Klartext-E-Mails verschlüsseln.

    from_db_value der EncryptedCharField fällt bei Klartext auf den Rohwert zurück,
    daher liest dieser Lauf sowohl alte (Klartext) als auch bereits verschlüsselte
    Werte korrekt; das erneute save() schreibt einheitlich verschlüsselt.
    """
    from ats.models import email_blind_index
    Applicant = apps.get_model("ats", "Applicant")
    for a in Applicant.objects.all().iterator():
        email = (a.email or "").strip().lower()
        a.email = email
        a.emailHash = email_blind_index(email)
        a.save(update_fields=["email", "emailHash"])


def noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0013_jobalertsubscription_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='emailHash',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=ats.models.EncryptedCharField(max_length=254),
        ),
        migrations.RunPython(backfill_email_hash_and_encrypt, noop),
    ]
