# Generated by Django 6.0.6 on 2026-07-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0014_applicant_emailhash_alter_applicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='requiresApproval',
            field=models.BooleanField(default=False),
        ),
    ]
