# Generated by Django 6.0.7 on 2026-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0014_jobalert_suchwort_verschluesselt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='nextAttemptAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['status', 'createdAt'], name='ats_aitask_claim_idx'),
        ),
    ]
