# Generated by Django 6.0.6 on 2026-07-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0015_facility_requiresapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='approvalChain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
