# Generated by Django 6.0.7 on 2026-08-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0015_ki_queue_backoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='descriptionEnglish',
            field=models.TextField(blank=True, null=True),
        ),
    ]
