# Generated by Django 6.0.6 on 2026-07-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0017_interviewslot_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='reminderSentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
