# Generated by Django 6.0.6 on 2026-07-02 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0018_interview_remindersentat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='interviewParticipations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
