# Generated by Django 6.0.6 on 2026-07-02 22:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0019_interview_participants_interviewslot_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('headcount', models.PositiveSmallIntegerField(default=1)),
                ('desiredStart', models.DateField(blank=True, null=True)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('ACCEPTED', 'Angenommen'), ('DECLINED', 'Abgelehnt'), ('CONVERTED', 'Ausschreibung erstellt')], default='OPEN', max_length=20)),
                ('decisionNote', models.TextField(blank=True, default='')),
                ('decidedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('decidedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decidedStaffingRequests', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffingRequests', to='ats.facility')),
                ('jobFamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ats.jobfamily')),
                ('requestedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffingRequests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
