# Generated by Django 6.0.6 on 2026-07-02 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0020_staffingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffingrequest',
            name='convertedJob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffingRequest', to='ats.jobposting'),
        ),
    ]
