# Generated by Django 6.0.6 on 2026-07-02 22:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0021_staffingrequest_convertedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPoolContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('jobPosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talentPoolContacts', to='ats.jobposting')),
                ('sentBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ats.talentpoolsubscription')),
            ],
            options={
                'unique_together': {('subscription', 'jobPosting')},
            },
        ),
    ]
