# Generated by Django 6.0.6 on 2026-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0022_talentpoolcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfamily',
            name='minimumQuestionsJson',
            field=models.TextField(default='[]'),
        ),
    ]
