# Generated by Django 6.0.6 on 2026-07-03 06:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0023_jobfamily_minimumquestionsjson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='panelUserIdsJson',
            field=models.TextField(default='[]'),
        ),
        migrations.CreateModel(
            name='ApplicationVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('FOR', 'Dafür'), ('AGAINST', 'Dagegen')], max_length=10)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ats.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationVotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('application', 'user')},
            },
        ),
    ]
