# Generated by Django 6.0.6 on 2026-07-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0024_jobposting_paneluseridsjson_applicationvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='panelUserIdsJson',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='facility',
            name='panelUserIdsJson',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='jobfamily',
            name='panelUserIdsJson',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='location',
            name='panelUserIdsJson',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='organization',
            name='panelUserIdsJson',
            field=models.TextField(default='[]'),
        ),
    ]
