# Generated by Django 6.0.6 on 2026-07-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0025_department_paneluseridsjson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brandAccent',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='organization',
            name='brandEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='brandHeroUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='brandLogoUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='brandMode',
            field=models.CharField(default='LIGHT', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='brandPrimary',
            field=models.CharField(default='#0065bd', max_length=9),
        ),
    ]
