# Generated by Django 6.0.6 on 2026-07-03 14:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0026_organization_brandaccent_organization_brandenabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
