# Generated by Django 6.0.6 on 2026-07-03 14:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0027_sourcechannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('headline', models.CharField(blank=True, default='', max_length=200)),
                ('introText', models.TextField(blank=True, default='')),
                ('heroUrl', models.CharField(blank=True, default='', max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('contactPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ats.contactperson')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ats.department')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ats.facility')),
                ('jobFamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ats.jobfamily')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ats.location')),
            ],
        ),
    ]
