# Generated by Django 6.0.6 on 2026-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0028_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='blocksJson',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='page',
            name='blocksJson',
            field=models.TextField(default='[]'),
        ),
    ]
