# Generated by Django 6.0.6 on 2026-07-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0030_page_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hiredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
