# Generated by Django 6.0.6 on 2026-07-04 15:31

import ats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0031_application_hiredat'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=ats.models.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sourcechannel',
            name='costAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
