# Generated by Django 6.0.6 on 2026-07-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0032_applicant_address_sourcechannel_costamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='headcount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
