# Generated by Django 6.0.6 on 2026-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0033_jobposting_headcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='panelDeadlineDays',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='panelQuorum',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
