# Generated by Django 6.0.6 on 2026-07-04 22:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0034_jobposting_paneldeadlinedays_jobposting_panelquorum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='requisitionChain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='staffingrequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Offen'), ('IN_APPROVAL', 'In Genehmigung'), ('RETURNED', 'Zur Nachbesserung'), ('ACCEPTED', 'Angenommen'), ('DECLINED', 'Abgelehnt'), ('CONVERTED', 'Ausschreibung erstellt')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='RequisitionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('APPROVED', 'Genehmigt'), ('RETURNED', 'Zur Nachbesserung'), ('REJECTED', 'Abgelehnt')], default='PENDING', max_length=20)),
                ('decidedAt', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('decidedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitionDecisions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ats.staffingrequest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
