# Generated by Django 6.0.6 on 2026-07-04 23:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0035_facility_requisitionchain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffingrequest',
            name='answersJson',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='staffingrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffingRequests', to='ats.department'),
        ),
        migrations.CreateModel(
            name='RequisitionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('chain', models.CharField(max_length=255)),
                ('formQuestionsJson', models.TextField(default='[]')),
                ('mandatory', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitionRules', to='ats.department')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitionRules', to='ats.facility')),
                ('jobFamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitionRules', to='ats.jobfamily')),
            ],
        ),
    ]
