# Generated by Django 6.0.6 on 2026-07-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0036_staffingrequest_answersjson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='expiresAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcechannel',
            name='expiresAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
