# Generated by Django 6.0.6 on 2026-07-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0037_landingpage_expiresat_sourcechannel_expiresat'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interviewRound',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='interviewRoundsJson',
            field=models.TextField(default='[]'),
        ),
    ]
