# Generated by Django 6.0.6 on 2026-07-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0038_application_interviewround_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionstep',
            name='viaDelegation',
            field=models.BooleanField(default=False),
        ),
    ]
