# Generated by Django 6.0.6 on 2026-07-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0039_requisitionstep_viadelegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionstep',
            name='groupQuorum',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
