# Generated by Django 6.0.6 on 2026-07-05 20:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0040_requisitionstep_groupquorum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.PositiveSmallIntegerField(default=0)),
                ('recommendation', models.CharField(choices=[('STRONG_YES', 'Klar dafür'), ('YES', 'Eher dafür'), ('NEUTRAL', 'Unentschieden'), ('NO', 'Eher dagegen'), ('STRONG_NO', 'Klar dagegen')], max_length=20)),
                ('ratingsJson', models.TextField(default='{}')),
                ('strengths', models.TextField(blank=True, default='')),
                ('concerns', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ats.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewFeedback', to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='ats.interview')),
            ],
            options={
                'ordering': ['round', 'createdAt'],
                'unique_together': {('application', 'author', 'round')},
            },
        ),
    ]
