# Generated by Django 6.0.6 on 2026-07-13 10:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0041_interviewfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('dueAt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('DONE', 'Erledigt')], default='OPEN', max_length=20)),
                ('doneAt', models.DateTimeField(blank=True, null=True)),
                ('sourceState', models.CharField(blank=True, default='', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowTasks', to='ats.application')),
                ('doneBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doneWorkflowTasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'dueAt', 'createdAt'],
            },
        ),
    ]
