# Generated by Django 6.0.6 on 2026-07-14 22:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0042_workflowtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPerformerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('dim', models.IntegerField(default=0)),
                ('vectorJson', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('jobFamily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bestPerformerProfiles', to='ats.jobfamily')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
