# Generated by Django 6.0.7 on 2026-07-20 11:15
# Ergänzt: Backfill der Sequenz für Bestandsketten. Die Ordnung wird entlang
# der Hash-Verweise rekonstruiert (prevHash -> entryHash), NICHT über
# createdAt – Timestamp-Kollisionen würden die historische Kettenordnung
# verfälschen und die Verifikation fälschlich anschlagen lassen.

from django.db import migrations, models


def backfill_seq(apps, schema_editor):
    AuditLog = apps.get_model("ats", "AuditLog")
    chained = [r for r in AuditLog.objects.all() if r.entryHash]
    by_prev = {}
    for r in chained:
        by_prev.setdefault(r.prevHash or "", []).append(r)
    # Kette vom Anfang (prevHash leer) entlang der Hash-Verweise ablaufen.
    ordered, seen, cursor = [], set(), ""
    while True:
        candidates = [r for r in by_prev.get(cursor, []) if r.id not in seen]
        if not candidates:
            break
        nxt = candidates[0]
        ordered.append(nxt)
        seen.add(nxt.id)
        cursor = nxt.entryHash
    # Reste (bereits gebrochene Ketten/Forks): stabil nach Zeit anhängen,
    # damit jede Zeile eine Sequenz erhält.
    rest = sorted((r for r in chained if r.id not in seen),
                  key=lambda r: (r.createdAt, str(r.id)))
    for i, r in enumerate(ordered + rest, start=1):
        r.seq = i
    AuditLog.objects.bulk_update(ordered + rest, ["seq"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0043_bestperformerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='seq',
            field=models.BigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(backfill_seq, migrations.RunPython.noop),
    ]
