# Generated by Django 6.0.7 on 2026-07-20 15:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0044_auditlog_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('tariffSystem', models.CharField(choices=[('TVOED', 'TVöD / TV-L'), ('AVR_CARITAS', 'AVR Caritas'), ('AVR_DIAKONIE', 'AVR Diakonie'), ('HAUSTARIF', 'Haustarif / eigenes Band')], default='HAUSTARIF', max_length=30)),
                ('minAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('maxAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('period', models.CharField(choices=[('MONTH', 'pro Monat'), ('YEAR', 'pro Jahr')], default='MONTH', max_length=10)),
                ('collectiveAgreement', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='payBand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobPostings', to='ats.payband'),
        ),
    ]
