# Generated by Django 6.0.7 on 2026-07-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0045_payband_jobposting_payband'),
    ]

    operations = [
        migrations.AddField(
            model_name='payband',
            name='criteriaEffort',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payband',
            name='criteriaResponsibility',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payband',
            name='criteriaSkills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payband',
            name='criteriaWorkingConditions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
